name: 'Blueskai Setup'
description: 'Setup environment for Blueskai'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Install dependencies
      shell: bash
      run: |
        uv venv
        uv sync

    - name: Download bsky-rmcp
      shell: bash
      run: |
        curl -L -o bin/bsky-rmcp https://github.com/sugyan/bsky-rmcp/releases/download/v0.0.5/bsky-rmcp
        chmod +x bin/bsky-rmcp
