name: Daily Post
description: This file will be rewritten from the script
'on':
  schedule:
  - cron: 39 3 * * *
  - cron: 31 4 * * *
  - cron: 48 4 * * *
  - cron: 51 13 * * *
  workflow_dispatch: null
jobs:
  setup:
    uses: ./.github/workflows/blueskai-setup.yml
  run-post:
    needs: setup
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BLUESKY_IDENTIFIER_0: ${{ secrets.BLUESKY_IDENTIFIER_0 }}
      BLUESKY_APP_PASSWORD_0: ${{ secrets.BLUESKY_APP_PASSWORD_0 }}
      BLUESKY_IDENTIFIER_1: ${{ secrets.BLUESKY_IDENTIFIER_1 }}
      BLUESKY_APP_PASSWORD_1: ${{ secrets.BLUESKY_APP_PASSWORD_1 }}
    steps:
    - name: Run post (profile 0)
      run: uv run python -m blueskai.main --profile 0 --instruction instructions/post.md
    - name: Run post (profile 1)
      run: uv run python -m blueskai.main --profile 1 --instruction instructions/post.md
