name: Daily Post
'on':
  schedule:
  - cron: 6 4 * * *
  - cron: 26 4 * * *
  - cron: 16 6 * * *
  - cron: 38 6 * * *
  - cron: 12 8 * * *
  - cron: 58 11 * * *
  - cron: 31 12 * * *
  workflow_dispatch: null
jobs:
  run-post:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BLUESKY_IDENTIFIER_0: ${{ secrets.BLUESKY_IDENTIFIER_0 }}
      BLUESKY_APP_PASSWORD_0: ${{ secrets.BLUESKY_APP_PASSWORD_0 }}
      BLUESKY_IDENTIFIER_1: ${{ secrets.BLUESKY_IDENTIFIER_1 }}
      BLUESKY_APP_PASSWORD_1: ${{ secrets.BLUESKY_APP_PASSWORD_1 }}
      EXPERTISE_MCP_URL: ${{ secrets.EXPERTISE_MCP_URL }}
      TZ: Asia/Tokyo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up
      uses: ./.github/actions/setup-blueskai
    - name: Run post 0
      run: uv run python -m blueskai.main --profile 0 --instruction instructions/post.md
    - name: Run post 1
      run: uv run python -m blueskai.main --profile 1 --instruction instructions/post.md
