name: Daily Post
description: This file will be updated daily by `scripts/update_schedule.py`
'on':
  schedule:
  - cron: 37 4 * * *
  - cron: 36 5 * * *
  - cron: 13 8 * * *
  - cron: 23 12 * * *
  workflow_dispatch: null
jobs:
  run-post:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BLUESKY_IDENTIFIER_0: ${{ secrets.BLUESKY_IDENTIFIER_0 }}
      BLUESKY_APP_PASSWORD_0: ${{ secrets.BLUESKY_APP_PASSWORD_0 }}
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up
      uses: ./.github/actions/setup-blueskai
    - name: Run post
      run: uv run python -m blueskai.main --profile 0 --instruction instructions/post.md
